Replace inline with __inline for C89 compatibility (#1250)
Hi Keith,

I'm investigating C89 compatibility issue in picolibc. I found that
signal.h uses the `inline` keyword in `__sigaddset` fucntion, and it
gives the below error

```
error: unknown type name 'inline'
  261 | static inline int
      |        ^
1 error generated.
```

So I was wondering is changing to __inline is better or guard it with
some macro based on the C version ?

Signed-off-by: mrashad46 <mrashad@synopsys.com>