github/workflows: Generate a docker image once and share it
This commit implements a prerequisite "cache-maker" job.  The job
generates a docker image file and store it in the GitHub Action Cache
for the subsequent jobs.  The subsequent jobs use the pre-generated
docker image by restoring from the cache.  This reduces the time spent
by Release test from 6.5 hours to 1.5 hours.

On each and every job, more than three and half minutes were spent for
generating the docker image. And the actual tests only take about 30
seconds (in case of non-multilib).  Multiply by 400 jobs, that's a
lot.

Before this design, we tried first-come first-generate approach.  But
those first-came jobs rushed to write the generated docker image to
the cache and created cache contentions. Jobs on the contentions took
8 min to finish, instead of 2 to 3 minutes without it.

We use docker/build-push-action[1] in the "cache-maker" job.  It is a
"GitHub Action to build and push Docker images with Buildx with full
support of the features provided by Moby BuildKit builder toolkit"
maintained by Docker.

As the name suggests, it builds and pushes docker images.  It seems
that's what many users do.  We, on the other hand, want to use the
built image without pushing it to a registry. We use this action
because it has an ability to generate a file containing a docker
image.  The file is then put in the cache for subsequent jobs.

The current version of buildx, the tool behind the action, already
have an experimental GitHub Action Cache support (type=gha)[2].
Unfortunately, it didn't work for our setup yet.  If we used with 400
jobs, we get the following error:

    Error: buildx failed with: error: failed to solve: failed to copy:
    invalid status response 416 The range specified is invalid for the
    current size of the resource. for
    https://aw97acprodeus1file2.blob.core.windows.net/....

It seems the type=gha works if it's used only by one job.  Thus, we
enabled it for caching docker build in the "cache-maker".

Because buildx is multi-platform by default[3], we set a single
platform "linux/amd64" for now.  docker output type doesn't support
multi-platform.  The setting is only for buildx internal.

[1]: https://github.com/docker/build-push-action
[2]: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api
[3]: https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images

Signed-off-by: Yasushi SHOJI <yashi@spacecubics.com>