Define _POSIX_C_SOURCE=200809L for symbols in that standard
This patch is required to get picolibc to compile with -Wall -Werror
-std=c99, otherwise it will complain about implicit function
declarations and similar:

picolibc/newlib/libc/string/strcasecmp_l.c:48:22: error: implicit declaration of function 'tolower_l' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
picolibc/newlib/libc/string/strcoll_l.c:43:49: error: declaration of 'struct __locale_t' will not be visible outside of this function [-Werror,-Wvisibility]