Add -semihost mode to gcc command line
The semihost library provides basic console i/o and 'exit' calls
underneath libc. Adding this library to the linker is a bit tricky as
we need to pull put __iob before libc is scanned (to avoid using the
weak __iob there), but then the rest of libsemihost is scanned after
libc so that any undefined reference to _exit gets resolved.

Signed-off-by: Keith Packard <keithp@keithp.com>