sys/unistd.h: fix definition of setproctitle_init
setproctitle_init is defined in c2x manner, omitting names for
the unused parameters.  This can result in warnings or errors
on certain compiler versions:

clang 8:

  error: parameter name omitted

clang 15:

  warning: omitting the parameter name in a function definition is a C2x
  extension [-Wc2x-extensions]

gcc -Wsystem-headers -pedantic -std=c17:

  warning: ISO C does not support omitting parameter names in function
  definitions before C2X [-Wpedantic]

Add parameters to avoid above warning and errors.

Fixes: 2e7f7b96e5f1 ("Cygwin: implement setproctitle")
Signed-off-by: Corinna Vinschen <corinna@vinschen.de>